package erc4337

const (
	ETHEREUM = "ETH_MAINNET"

	//L2s
	BASE     = "BASE"
	POLYGON  = "POLYGON_POS"
	OPTIMISM = "OPTIMISM"

	// TESTNETS
	MUMBAI          = "POLYGON_MUMBAI"
	GOERLI          = "GOERLI"
	BASE_GOERLI     = "BASE_GOERLI"
	OPTIMISM_GOERLI = "OPTIMISM_GOERLI"
)
