// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	Address       string  `json:"address"`
	SignerAddress *string `json:"signerAddress,omitempty"`
}

type NewSubscription struct {
	Amount             float64 `json:"amount"`
	DestinationAddress string  `json:"destinationAddress"`
	FromAddress        string  `json:"fromAddress"`
	Interval           int     `json:"interval"`
}
