// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Account struct {
	Email   *string `json:"email,omitempty"`
	Address string  `json:"address"`
	Signer  *string `json:"signer,omitempty"`
}

type NewSubscription struct {
	Chain         int        `json:"chain"`
	NextChargeAt  *time.Time `json:"nextChargeAt,omitempty"`
	Token         string     `json:"token"`
	Amount        int        `json:"amount"`
	Interval      int        `json:"interval"`
	ProductID     string     `json:"productId"`
	WalletAddress string     `json:"walletAddress"`
	OwnerAddress  string     `json:"ownerAddress"`
}

type NewTransferRequest struct {
	Chain  int     `json:"chain"`
	Token  string  `json:"token"`
	Amount float64 `json:"amount"`
	Sender string  `json:"sender"`
	Target string  `json:"target"`
}

type RequestValidation struct {
	Chain         int    `json:"chain"`
	UserOpHash    string `json:"userOpHash"`
	SignedMessage string `json:"signedMessage"`
}

type SubscriptionData struct {
	ID              string  `json:"id"`
	Token           string  `json:"token"`
	Amount          int     `json:"amount"`
	Interval        int     `json:"interval"`
	ProductID       string  `json:"productId"`
	WalletAddress   string  `json:"walletAddress"`
	SubscriptionKey string  `json:"subscriptionKey"`
	CreatedAt       *string `json:"createdAt,omitempty"`
}

type TransactionData struct {
	Chain             int      `json:"chain"`
	Token             *string  `json:"token,omitempty"`
	Amount            *float64 `json:"Amount,omitempty"`
	Recipient         *string  `json:"Recipient,omitempty"`
	TransactionHash   string   `json:"TransactionHash"`
	BlockExplorerLink string   `json:"BlockExplorerLink"`
}

type ValidationData struct {
	UserOpHash string `json:"userOpHash"`
}
