// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AccessKey struct {
	PublicKey  string `json:"publicKey"`
	PrivateKey string `json:"privateKey"`
}

type Merchant struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Email      string `json:"email"`
	PublicKey  string `json:"publicKey"`
	WebHookURL string `json:"webHookUrl"`
}

type MerchantStats struct {
	Users         int `json:"users"`
	Products      int `json:"products"`
	Subscriptions int `json:"subscriptions"`
}

type MerchantUpdate struct {
	MerchantID string  `json:"merchantId"`
	Name       *string `json:"name,omitempty"`
	Email      *string `json:"email,omitempty"`
	IsActive   *bool   `json:"isActive,omitempty"`
	WebHookURL *string `json:"webHookUrl,omitempty"`
}

type NewMerchant struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	Owner string `json:"owner"`
	// This would be the url where payment status event would be delivered to
	WebHookURL *string `json:"webHookUrl,omitempty"`
	// This would be the email where transaction receipt replies would be delivered to
	SupportEmail *string `json:"supportEmail,omitempty"`
}

type NewProduct struct {
	Name             string `json:"name"`
	Owner            string `json:"owner"`
	Chain            int    `json:"chain"`
	Token            string `json:"token"`
	ReceivingAddress string `json:"receivingAddress"`
}

type Product struct {
	Name             string  `json:"name"`
	Owner            string  `json:"owner"`
	Chain            int     `json:"chain"`
	Token            string  `json:"token"`
	ProductID        string  `json:"ProductId"`
	ReceivingAddress string  `json:"receivingAddress"`
	Subscriptions    []*Sub  `json:"subscriptions,omitempty"`
	CreatedAt        *string `json:"createdAt,omitempty"`
}

type ProductUpdate struct {
	Name             *string `json:"name,omitempty"`
	ReceivingAddress *string `json:"receivingAddress,omitempty"`
}

type Sub struct {
	Chain         int    `json:"chain"`
	Token         string `json:"token"`
	Amount        int    `json:"amount"`
	Active        bool   `json:"active"`
	Interval      string `json:"interval"`
	WalletAddress string `json:"walletAddress"`
}
