// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	Email   *string `json:"email,omitempty"`
	Address string  `json:"address"`
}

type NewSubscription struct {
	Token              string  `json:"token"`
	Amount             float64 `json:"amount"`
	Interval           int     `json:"interval"`
	OriginAddress      string  `json:"originAddress"`
	DestinationAddress string  `json:"destinationAddress"`
}

type SubscriptionData struct {
	ID                 string  `json:"id"`
	Token              string  `json:"token"`
	Amount             float64 `json:"amount"`
	Interval           int     `json:"interval"`
	OriginAddress      string  `json:"originAddress"`
	DestinationAddress string  `json:"destinationAddress"`
}
