// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	Email   *string `json:"email,omitempty"`
	Address string  `json:"address"`
	Signer  *string `json:"signer,omitempty"`
}

type NewSubscription struct {
	Token         string  `json:"token"`
	Amount        float64 `json:"amount"`
	Interval      int     `json:"interval"`
	MerchantID    string  `json:"merchantId"`
	WalletAddress string  `json:"walletAddress"`
}

type SubscriptionData struct {
	ID            string  `json:"id"`
	Token         string  `json:"token"`
	Amount        float64 `json:"amount"`
	Interval      int     `json:"interval"`
	MerchantID    string  `json:"merchantId"`
	WalletAddress string  `json:"walletAddress"`
}
